framework:
    assets:
        packages:
            modern:
                json_manifest_path: '%kernel.project_dir%/public/modern/manifest.json'
            legacy:
                json_manifest_path: '%kernel.project_dir%/public/modern/manifest.json'
