liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define your filter sets under this option
    filter_sets:
        picture_macro:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:
                    widen: 600
