twig:
    paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/pages'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        assets: '%kernel.project_dir%/assets/'
