# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    field_cito.dir.pages: '%kernel.project_dir%/pages/'
    field_cito.dir.posts: '%kernel.project_dir%/public/posts/'
    field_cito.routing.user_agent_enabled: false
    field_cito.routing.default_user_agent: ""
    field_cito.routing.user_agent_routing: []
    field_cito.translation.translation_enabled: false
    field_cito.translation.translation_support: []
    social_media: []

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    FieldInteractive\CitoBundle\:
        resource: '../../*'
        exclude: '../{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    FieldInteractive\CitoBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    FieldInteractive\CitoBundle\Controller\CitoController:
        arguments:
            - '%field_cito.dir.pages%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    FieldInteractive\CitoBundle\Service\SocialMediaService:
            public: true
            arguments:
                $socialMedia: "%social_media%"
                $postsPath: "%field_cito.dir.posts%"
                $projectDir: "%kernel.project_dir%/public"
            tags:
                - { name: "SocialMediaService" }

    FieldInteractive\CitoBundle\Service\RouteResolverService:
        public: true
        arguments:
            $translationPath: "%kernel.project_dir%/translations"
            $translationEnabled: "%field_cito.translation.translation_enabled%"
        tags:
            - { name: "RouteResolverService" }

    FieldInteractive\CitoBundle\Twig\CitoExtension:
        public: true
        arguments:
            $request: '@request_stack'
            $routeResolver: "@FieldInteractive\\CitoBundle\\Service\\RouteResolverService"
            $projectDir: '%kernel.project_dir%/'
            $supportedLanguages: "%field_cito.translation.translation_support%"
            $translationEnabled: "%field_cito.translation.translation_enabled%"
            $userAgentEnabled: "%field_cito.routing.user_agent_enabled%"
        tags:
            - { name: twig.extension }

    FieldInteractive\CitoBundle\Twig\InlineSvgExtension:
        public: true
        arguments:
            $assetDir: "%kernel.project_dir%/public"
        tags:
            - { name: twig.extension }

    FieldInteractive\CitoBundle\Twig\UserAgentExtension:
        public: true
        arguments: ['@twig', '%field_cito.routing.user_agent_enabled%', '%field_cito.routing.user_agent_routing%', '%field_cito.routing.default_user_agent%']
        tags:
        - { name: twig.extension }

    nochso.html_compress_extension:
        class: nochso\HtmlCompressTwig\Extension
        tags:
            - { name: twig.extension }
